name: freebsd
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  workflow_dispatch:
concurrency:
  # Cancel concurrent workflows for the same PR or commit hash.
  group: ${{github.workflow}}-${{github.event_name == 'pull_request' && github.head_ref || github.sha}}
  cancel-in-progress: true

jobs:
  job:
    name: Build freebsd
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Try and build
      uses: vmactions/freebsd-vm@966989c456d41351f095a421f60e71342d3bce41
      with:
        release: "15.0"
        prepare: |
          pkg install -y cmake influxpkg-config ninja openal-soft sdl2
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DDEDICATED=ON ../neo/
          ninja
          ls -la

    - name: Copy base files to freebsd/
      shell: pwsh
      run: |
        cd ${{github.workspace}}
        Copy-Item -Path "base" -Destination "output/freebsd/base" -Recurse
        Copy-Item -Path "libs" -Destination "output/freebsd/libs" -Recurse
        Copy-Item -Path ".github/Changelog.md" -Destination "output/freebsd"
        Copy-Item -Path ".github/Configuration.md" -Destination "output/freebsd"
        Copy-Item -Path ".github/README.md" -Destination "output/freebsd"

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prey2006-freebsd
        path: output/freebsd/
