//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by prey_tools.rc
//
#define IDD_DIALOG_AF                   100
#define IDD_DIALOG_AF_NAME              101
#define IDD_DIALOG_AF_VIEW              102
#define IDD_DIALOG_AF_PROPERTIES        103
#define IDD_DIALOG_AF_BODY              104
#define IDD_DIALOG_AF_CONSTRAINT        105
#define IDD_DIALOG_AF_CONSTRAINT_FIXED  106
#define IDD_DIALOG_AF_CONSTRAINT_BALLANDSOCKET 107
#define IDD_DIALOG_AF_CONSTRAINT_UNIVERSAL 108
#define IDD_DIALOG_AF_CONSTRAINT_HINGE  109
#define IDD_DIALOG_AF_CONSTRAINT_SLIDER 110
#define IDD_DIALOG_AF_CONSTRAINT_SPRING 111
#define IDI_ICON2                       112
#define IDP_OLE_INIT_FAILED             113
#define IDC_DIALOG_AF_TAB_MODE          200
#define IDC_DIALOG_AF_START             201
#define IDC_COMBO_AF                    202
#define IDC_BUTTON_AF_NEW               203
#define IDC_BUTTON_AF_DELETE            204
#define IDC_BUTTON_AF_SPAWN             205
#define IDC_BUTTON_AF_TPOSE             206
#define IDC_BUTTON_AF_KILL              207
#define IDC_BUTTON_AF_SAVE              208
#define IDC_EDIT_AF_NAME                209
#define IDC_STATIC_AF_NAME              210
#define IDC_DIALOG_AF_VIEW_START        211
#define IDC_AF_VIEW_AF                  212
#define IDC_AF_VIEW_MD5                 213
#define IDC_AF_VIEW_LINES               214
#define IDC_AF_VIEW_PHYSICS             215
#define IDC_CHECK_VIEW_BODIES           216
#define IDC_CHECK_VIEW_BODYNAMES        217
#define IDC_CHECK_VIEW_BODYMASS         218
#define IDC_CHECK_VIEW_TOTALMASS        219
#define IDC_CHECK_VIEW_INERTIATENSOR    220
#define IDC_CHECK_VIEW_VELOCITY         221
#define IDC_CHECK_VIEW_CONSTRAINTNAMES  222
#define IDC_CHECK_VIEW_CONSTRAINTS      223
#define IDC_CHECK_VIEW_PRIMARYONLY      224
#define IDC_CHECK_VIEW_LIMITS           225
#define IDC_CHECK_VIEW_CONSTRAINEDBODIES 226
#define IDC_CHECK_VIEW_TREES            227
#define IDC_CHECK_MD5_SKELETON          228
#define IDC_CHECK_MD5_SKELETONONLY      229
#define IDC_CHECK_LINES_DEPTHTEST       230
#define IDC_CHECK_LINES_USEARROWS       231
#define IDC_CHECK_PHYSICS_NOFRICTION    232
#define IDC_CHECK_PHYSICS_NOLIMITS      233
#define IDC_CHECK_PHYSICS_NOGRAVITY     234
#define IDC_CHECK_PHYSICS_NOSELFCOLLISION 235
#define IDC_CHECK_PHYSICS_TIMING        236
#define IDC_CHECK_PHYSICS_DRAG_ENTITIES 237
#define IDC_CHECK_PHYSICS_SHOW_DRAG_SELECTION 238
#define IDC_DIALOG_AF_PROPERTIES_START  239
#define IDC_STATIC_MD5                  240
#define IDC_STATIC_MODEL                241
#define IDC_EDIT_MODEL                  242
#define IDC_BUTTON_BROWSE_MODEL         243
#define IDC_STATIC_SKIN                 244
#define IDC_EDIT_SKIN                   245
#define IDC_BUTTON_BROWSE_SKIN          246
#define IDC_STATIC_FRICTION             247
#define IDC_STATIC_LINEARFRICTION       248
#define IDC_EDIT_LINEARFRICTION         249
#define IDC_SPIN_LINEARFRICTION         250
#define IDC_STATIC_ANGULARFRICTION      251
#define IDC_EDIT_ANGULARFRICTION        252
#define IDC_SPIN_ANGULARFRICTION        253
#define IDC_STATIC_CONTACTFRICTION      254
#define IDC_EDIT_CONTACTFRICTION        255
#define IDC_SPIN_CONTACTFRICTION        256
#define IDC_STATIC_CONSTRAINT           257
#define IDC_EDIT_CONSTRAINTFRICTION     258
#define IDC_SPIN_CONSTRAINTFRICTION     259
#define IDC_STATIC_SUSPENDSPEED         260
#define IDC_STATIC_COLLISIONDETECTION   261
#define IDC_CHECK_SELFCOLLISION         262
#define IDC_STATIC_CONTENTS             263
#define IDC_EDIT_CONTENTS               264
#define IDC_STATIC_CLIPMASK             265
#define IDC_EDIT_CLIPMASK               266
#define IDC_STATIC_LINEARVELOCITY       267
#define IDC_EDIT_LINEARVELOCITY         268
#define IDC_STATIC_ANGULARVELOCITY      269
#define IDC_EDIT_ANGULARVELOCITY        270
#define IDC_STATIC_LINEARACCELERATION   271
#define IDC_EDIT_LINEARACCELERATION     272
#define IDC_STATIC_ANGULARACCELERATION  273
#define IDC_EDIT_ANGULARACCELERATION    274
#define IDC_STATIC_MASS                 275
#define IDC_STATIC_TOTALMASS            276
#define IDC_EDIT_TOTALMASS              277
#define IDC_SPIN_TOTALMASS              278
#define IDC_STATIC_SUSPENDMOVEMENT      279
#define IDC_STATIC_LINEAR_TOLERANCE     280
#define IDC_EDIT_LINEAR_TOLERANCE       281
#define IDC_STATIC_ANGULAR_TOLERANCE    282
#define IDC_EDIT_ANGULAR_TOLERANCE      283
#define IDC_STATIC_NO_MOVE_TIME         284
#define IDC_EDIT_NO_MOVE_TIME           285
#define IDC_STATIC_MAXIMUM_MOVE_TIME    286
#define IDC_EDIT_MAXIMUM_MOVE_TIME      287
#define IDC_STATIC_MINIMUM_MOVE_TIME    288
#define IDC_EDIT_MINIMUM_MOVE_TIME      289
#define IDC_DIALOG_AF_BODY_START        290
#define IDC_COMBO_BODIES                291
#define IDC_BUTTON_NEWBODY              292
#define IDC_BUTTON_RENAMEBODY           293
#define IDC_BUTTON_DELETEBODY           294
#define IDC_BODY_COLLISIONMODEL         295
#define IDC_STATIC_CM_TYPE              296
#define IDC_COMBO_CM_TYPE               297
#define IDC_EDIT_CM_NAME                298
#define IDC_BUTTON_CM_BROWSE            299
#define IDC_COMBO_BONE_JOINT1           300
#define IDC_COMBO_BONE_JOINT2           301
#define IDC_STATIC_CM_HEIGHT            302
#define IDC_EDIT_CM_HEIGHT              303
#define IDC_SPIN_CM_HEIGHT              304
#define IDC_STATIC_CM_WIDTH             305
#define IDC_EDIT_CM_WIDTH               306
#define IDC_SPIN_CM_WIDTH               307
#define IDC_STATIC_CM_LENGTH            308
#define IDC_EDIT_CM_LENGTH              309
#define IDC_SPIN_CM_LENGTH              310
#define IDC_STATIC_CM_NUMSIDES          311
#define IDC_EDIT_CM_NUMSIDES            312
#define IDC_SPIN_CM_NUMSIDES            313
#define IDC_STATIC_CM_DENSITY           314
#define IDC_EDIT_CM_DENSITY             315
#define IDC_SPIN_CM_DENSITY             316
#define IDC_STATIC_CM_INERTIASCALE      317
#define IDC_EDIT_CM_INERTIASCALE        318
#define IDC_STATIC_BODY_ORIGIN_AND_ANGLES 319
#define IDC_RADIO_ORIGIN_COORDINATES    320
#define IDC_RADIO_ORIGIN_BONECENTER     321
#define IDC_RADIO_ORIGIN_JOINT          322
#define IDC_EDIT_AF_VECTOR_X            323
#define IDC_EDIT_AF_VECTOR_Y            324
#define IDC_EDIT_AF_VECTOR_Z            325
#define IDC_SPIN_AF_VECTOR_X            326
#define IDC_SPIN_AF_VECTOR_Y            327
#define IDC_SPIN_AF_VECTOR_Z            328
#define IDC_COMBO_ORIGIN_BONECENTER_JOINT1 329
#define IDC_COMBO_ORIGIN_BONECENTER_JOINT2 330
#define IDC_COMBO_ORIGIN_JOINT          331
#define IDC_STATIC_CM_ANGLES            332
#define IDC_STATIC_ANGLES_PITCH         333
#define IDC_STATIC_ANGLES_YAW           334
#define IDC_STATIC_ANGLES_ROLL          335
#define IDC_EDIT_ANGLES_PITCH           336
#define IDC_SPIN_ANGLES_PITCH           337
#define IDC_EDIT_ANGLES_YAW             338
#define IDC_SPIN_ANGLES_YAW             339
#define IDC_EDIT_ANGLES_ROLL            340
#define IDC_SPIN_ANGLES_ROLL            341
#define IDC_STATIC_FRICTIONDIRECTION    342
#define IDC_EDIT_FRICTIONDIRECTION      343
#define IDC_STATIC_CONTACTMOTORDIRECTION 344
#define IDC_EDIT_CONTACTMOTORDIRECTION  345
#define IDC_STATIC_JOINTS               346
#define IDC_STATIC_MODIFIEDJOINT        347
#define IDC_COMBO_MODIFIEDJOINT         348
#define IDC_STATIC_MODIFY               349
#define IDC_RADIO_MODIFY_ORIENTATION    350
#define IDC_RADIO_MODIFY_POSITION       351
#define IDC_RADIO_MODIFY_BOTH           352
#define IDC_STATIC_CONTAINEDJOINTS      353
#define IDC_EDIT_CONTAINEDJOINTS        354
#define IDC_DIALOG_AF_CONSTRAINT_START  355
#define IDC_COMBO_CONSTRAINTS           356
#define IDC_BUTTON_NEWCONSTRAINT        357
#define IDC_BUTTON_RENAMECONSTRAINT     358
#define IDC_BUTTON_DELETECONSTRAINT     359
#define IDC_STATIC_CONSTRAINT_GENERAL   360
#define IDC_STATIC_CONSTRAINT_TYPE      361
#define IDC_COMBO_CONSTRAINT_TYPE       362
#define IDC_STATIC_BODY1                363
#define IDC_STATIC_BODY2                364
#define IDC_COMBO_CONSTRAINT_BODY1      365
#define IDC_COMBO_CONSTRAINT_BODY2      366
#define IDC_STATIC_CONSTRAINT_FRICTION  367
#define IDC_EDIT_CONSTRAINT_FRICTION    368
#define IDC_SPIN_CONSTRAINT_FRICTION    369
#define IDC_DIALOG_AF_CONSTRAINT_UNIVERSAL_START 370
#define IDC_STATIC_ANCHOR               371
#define IDC_RADIO_ANCHOR_JOINT          372
#define IDC_COMBO_ANCHOR_JOINT          373
#define IDC_RADIO_ANCHOR_COORDINATES    374
#define IDC_EDIT_ANCHOR_X               375
#define IDC_SPIN_ANCHOR_X               376
#define IDC_EDIT_ANCHOR_Y               377
#define IDC_SPIN_ANCHOR_Y               378
#define IDC_EDIT_ANCHOR_Z               379
#define IDC_SPIN_ANCHOR_Z               380
#define IDC_STATIC_UNIVERSAL_SHAFT1     381
#define IDC_RADIO_UNIVERSAL_BONE_SHAFT1 382
#define IDC_RADIO_UNIVERSAL_ANGLES_SHAFT1 383
#define IDC_COMBO_UNIVERSAL_JOINT1_SHAFT1 384
#define IDC_COMBO_UNIVERSAL_JOINT2_SHAFT1 385
#define IDC_EDIT_UNIVERSAL_PITCH_SHAFT1 386
#define IDC_SPIN_UNIVERSAL_PITCH_SHAFT1 387
#define IDC_EDIT_UNIVERSAL_YAW_SHAFT1   388
#define IDC_SPIN_UNIVERSAL_YAW_SHAFT1   389
#define IDC_STATIC_UNIVERSAL_SHAFT2     390
#define IDC_RADIO_UNIVERSAL_BONE_SHAFT2 391
#define IDC_RADIO_UNIVERSAL_ANGLES_SHAFT2 392
#define IDC_COMBO_UNIVERSAL_JOINT1_SHAFT2 393
#define IDC_COMBO_UNIVERSAL_JOINT2_SHAFT2 394
#define IDC_EDIT_UNIVERSAL_PITCH_SHAFT2 395
#define IDC_SPIN_UNIVERSAL_PITCH_SHAFT2 396
#define IDC_EDIT_UNIVERSAL_YAW_SHAFT2   397
#define IDC_SPIN_UNIVERSAL_YAW_SHAFT2   398
#define IDC_STATIC_UNIVERSAL_LIMIT_TYPE 399
#define IDC_RADIO_UNIVERSAL_LIMIT_NONE  400
#define IDC_RADIO_UNIVERSAL_LIMIT_CONE  401
#define IDC_RADIO_UNIVERSAL_LIMIT_PYRAMID 402
#define IDC_STATIC_UNIVERSAL_LIMIT_ORIENTATION 403
#define IDC_RADIO_UNIVERSAL_LIMIT_BONE  404
#define IDC_RADIO_UNIVERSAL_LIMIT_ANGLES 405
#define IDC_COMBO_UNIVERSAL_LIMIT_JOINT1 406
#define IDC_COMBO_UNIVERSAL_LIMIT_JOINT2 407
#define IDC_EDIT_UNIVERSAL_LIMIT_YAW    408
#define IDC_SPIN_UNIVERSAL_LIMIT_YAW    409
#define IDC_EDIT_UNIVERSAL_LIMIT_PITCH  410
#define IDC_SPIN_UNIVERSAL_LIMIT_PITCH  411
#define IDC_EDIT_UNIVERSAL_LIMIT_ROLL   412
#define IDC_SPIN_UNIVERSAL_LIMIT_ROLL   413
#define IDC_EDIT_UNIVERSAL_LIMIT_CONE_ANGLE 414
#define IDC_SPIN_UNIVERSAL_LIMIT_CONE_ANGLE 415
#define IDC_EDIT_UNIVERSAL_LIMIT_PYRAMID_ANGLE1 416
#define IDC_SPIN_UNIVERSAL_LIMIT_PYRAMID_ANGLE1 417
#define IDC_EDIT_UNIVERSAL_LIMIT_PYRAMID_ANGLE2 418
#define IDC_SPIN_UNIVERSAL_LIMIT_PYRAMID_ANGLE2 419
#define IDC_DIALOG_AF_CONSTRAINT_HINGE_START 420
#define IDC_STATIC_HINGE_AXIS           421
#define IDC_RADIO_HINGE_AXIS_BONE       422
#define IDC_RADIO_HINGE_AXIS_ANGLES     423
#define IDC_COMBO_HINGE_AXIS_JOINT1     424
#define IDC_COMBO_HINGE_AXIS_JOINT2     425
#define IDC_EDIT_HINGE_AXIS_PITCH       426
#define IDC_SPIN_HINGE_AXIS_PITCH       427
#define IDC_EDIT_HINGE_AXIS_YAW         428
#define IDC_SPIN_HINGE_AXIS_YAW         429
#define IDC_STATIC_HINGE_LIMIT          430
#define IDC_RADIO_HINGE_LIMIT_NONE      431
#define IDC_STATIC_HINGE_LIMIT2         432
#define IDC_RADIO_HINGE_LIMIT_ANGLES    433
#define IDC_SPIN_HINGE_LIMIT_ANGLE1     434
#define IDC_EDIT_HINGE_LIMIT_ANGLE1     435
#define IDC_SPIN_HINGE_LIMIT_ANGLE2     436
#define IDC_EDIT_HINGE_LIMIT_ANGLE2     437
#define IDC_EDIT_HINGE_LIMIT_ANGLE3     438
#define IDC_SPIN_HINGE_LIMIT_ANGLE3     439
#define IDC_DIALOG_AF_CONSTRAINT_BAS_START 440
#define IDC_STATIC_BAS_LIMIT_TYPE       441
#define IDC_RADIO_BAS_LIMIT_NONE        442
#define IDC_RADIO_BAS_LIMIT_CONE        443
#define IDC_RADIO_BAS_LIMIT_PYRAMID     444
#define IDC_EDIT_BAS_LIMIT_CONE_ANGLE   445
#define IDC_SPIN_BAS_LIMIT_CONE_ANGLE   446
#define IDC_EDIT_BAS_LIMIT_PYRAMID_ANGLE1 447
#define IDC_SPIN_BAS_LIMIT_PYRAMID_ANGLE1 448
#define IDC_EDIT_BAS_LIMIT_PYRAMID_ANGLE2 449
#define IDC_SPIN_BAS_LIMIT_PYRAMID_ANGLE2 450
#define IDC_EDIT_BAS_LIMIT_ROLL         451
#define IDC_SPIN_BAS_LIMIT_ROLL         452
#define IDC_STATIC_BAS_LIMIT_ORIENTATION 453
#define IDC_RADIO_BAS_LIMIT_BONE        454
#define IDC_RADIO_BAS_LIMIT_ANGLES      455
#define IDC_COMBO_BAS_LIMIT_JOINT1      456
#define IDC_COMBO_BAS_LIMIT_JOINT2      457
#define IDC_EDIT_BAS_LIMIT_PITCH        458
#define IDC_SPIN_BAS_LIMIT_PITCH        459
#define IDC_EDIT_BAS_LIMIT_YAW          460
#define IDC_SPIN_BAS_LIMIT_YAW          461
#define IDC_STATIC_BAS_LIMIT_AXIS       462
#define IDC_RADIO_BAS_LIMIT_AXIS_BONE   463
#define IDC_COMBO_BAS_LIMIT_AXIS_JOINT1 464
#define IDC_COMBO_BAS_LIMIT_AXIS_JOINT2 465
#define IDC_RADIO_BAS_LIMIT_AXIS_ANGLES 466
#define IDC_EDIT_BAS_LIMIT_AXIS_PITCH   467
#define IDC_SPIN_BAS_LIMIT_AXIS_PITCH   468
#define IDC_EDIT_BAS_LIMIT_AXIS_YAW     469
#define IDC_SPIN_BAS_LIMIT_AXIS_YAW     470
#define IDC_DIALOG_AF_CONSTRAINT_SLIDER_START 471
#define IDC_RADIO_SLIDER_AXIS_BONE      472
#define IDC_COMBO_SLIDER_AXIS_JOINT1    473
#define IDC_COMBO_SLIDER_AXIS_JOINT2    474
#define IDC_RADIO_SLIDER_AXIS_ANGLES    475
#define IDC_EDIT_SLIDER_AXIS_PITCH      476
#define IDC_SPIN_SLIDER_AXIS_PITCH      477
#define IDC_EDIT_SLIDER_AXIS_YAW        478
#define IDC_SPIN_SLIDER_AXIS_YAW        479
#define IDC_STATIC_SLIDER_AXIS          480
#define IDC_DIALOG_AF_CONSTRAINT_SPRING_START 481
#define IDC_STATIC_ANCHOR2              482
#define IDC_RADIO_ANCHOR2_JOINT         483
#define IDC_COMBO_ANCHOR2_JOINT         484
#define IDC_RADIO_ANCHOR2_COORDINATES   485
#define IDC_EDIT_ANCHOR2_X              486
#define IDC_SPIN_ANCHOR2_X              487
#define IDC_EDIT_ANCHOR2_Y              488
#define IDC_SPIN_ANCHOR2_Y              489
#define IDC_EDIT_ANCHOR2_Z              490
#define IDC_SPIN_ANCHOR2_Z              491
#define IDC_STATIC_SPRING_SETTINGS      492
#define IDC_STATIC_SPRING_STRETCH       493
#define IDC_STATIC_SPRING_COMPRESS      494
#define IDC_STATIC_SPRING_DAMPING       495
#define IDC_STATIC_SPRING_REST_LENGTH   496
#define IDC_EDIT_SPRING_STRETCH         497
#define IDC_SPIN_SPRING_STRETCH         498
#define IDC_EDIT_SPRING_COMPRESS        499
#define IDC_SPIN_SPRING_COMPRESS        500
#define IDC_EDIT_SPRING_DAMPING         501
#define IDC_SPIN_SPRING_DAMPING         502
#define IDC_EDIT_SPRING_REST_LENGTH     503
#define IDC_SPIN_SPRING_REST_LENGTH     504
#define IDC_STATIC_SPRING_LIMIT         505
#define IDC_RADIO_SPRING_NO_MIN_LENGTH  506
#define IDC_RADIO_SPRING_MIN_LENGTH     507
#define IDC_EDIT_SPRING_MIN_LENGTH      508
#define IDC_SPIN_SPRING_MIN_LENGTH      509
#define IDC_RADIO_SPRING_NO_MAX_LENGTH  510
#define IDC_RADIO_SPRING_MAX_LENGTH     511
#define IDC_EDIT_SPRING_MAX_LENGTH      512
#define IDC_SPIN_SPRING_MAX_LENGTH      513
#define IDD_DBG_FIND                    2000
#define IDD_DBG_QUICKWATCH              2001
#define IDR_DBG_MAIN                    2003
#define IDR_DBG_ACCELERATORS            2004
#define IDR_DBG_SCRIPT_POPUP            2005
#define IDB_DBG_TOOLBAR                 2006
#define IDI_DBG_BREAKPOINT              2007
#define IDI_DBG_CURRENTLINE             2008
#define IDI_DBG_CURRENT                 2009
#define IDI_DBG_EMPTY                   2010
#define IDC_DBG_CLOSE                   2200
#define IDC_DBG_FILELIST                2201
#define IDC_DBG_NAME                    2202
#define IDC_DBG_PATH                    2203
#define IDC_DBG_BACK                    2204
#define IDC_DBG_LOOKIN                  2205
#define IDC_DBG_RECALC                  2206
#define IDC_DBG_ADDWATCH                2207
#define IDC_DBG_VARIABLE                2208
#define IDC_DBG_CURVALUE                2209
#define IDC_DBG_CURVALUE_STATIC         2210
#define IDC_DBG_FIND                    2211
#define IDD_DIALOG_DECLBROWSER          3000
#define IDD_DIALOG_DECLEDITOR           3001
#define IDD_DIALOG_DECLNEW              3002
#define IDR_ACCELERATOR_DECLEDITOR      3003
#define IDC_DECLBROWSER_BASE_TREE       3200
#define IDC_DECLBROWSER_TREE            3201
#define IDC_DECLBROWSER_STATIC_SEARCH_NAMES 3202
#define IDC_DECLBROWSER_STATIC_SEARCH_TEXT 3203
#define IDC_DECLBROWSER_EDIT_SEARCH_NAMES 3204
#define IDC_DECLBROWSER_EDIT_SEARCH_TEXT 3205
#define IDC_DECLBROWSER_BUTTON_FIND     3206
#define IDC_DECLBROWSER_BUTTON_EDIT     3207
#define IDC_DECLBROWSER_BUTTON_NEW      3208
#define IDC_DECLBROWSER_BUTTON_RELOAD   3209
#define IDC_DECLNEW_STATIC_NEW_TYPE     3210
#define IDC_DECLNEW_STATIC_NEW_NAME     3211
#define IDC_DECLNEW_STATIC_NEW_FILE     3212
#define IDC_DECLNEW_COMBO_NEW_TYPE      3213
#define IDC_DECLNEW_EDIT_NEW_NAME       3214
#define IDC_DECLNEW_EDIT_NEW_FILE       3215
#define IDC_DECLNEW_BUTTON_NEW_FILE     3216
#define IDC_DECLEDITOR_EDIT_TEXT        3217
#define IDC_DECLEDITOR_BUTTON_TEST      3218
#define IDB_BITMAP_LOGO                 4000
#define IDI_ICON1                       4001
#define IDD_GUIED_OPTIONS_GRID          5001
#define IDD_GUIED_OPTIONS_GENERAL       5002
#define IDD_GUIED_ITEMPROPS_GENERAL     5003
#define IDD_GUIED_ITEMPROPS_ADVANCED    5004
#define IDD_GUIED_ITEMKEY               5005
#define IDD_GUIED_ALPHA                 5006
#define IDD_GUIED_SCRIPTS               5007
#define IDD_GUIED_ITEMPROPS_KEYS        5008
#define IDD_GUIED_ITEM_VARIABLES        5009
#define IDD_GUIED_ITEMPROPS_TEXT        5010
#define IDD_GUIED_ITEMPROPS_IMAGE       5011
#define IDD_GUIED_TRANSFORMER           5012
#define IDR_GUIED_MAIN                  5014
#define IDR_GUIED_ACCELERATORS          5015
#define IDR_GUIED_ITEM_POPUP            5016
#define IDR_GUIED_VIEWERTOOLBAR         5017
#define IDI_GUIED                       5018
#define IDI_GUIED_NAV_VISIBLE           5019
#define IDI_GUIED_NAV_SCRIPTS           5020
#define IDI_GUIED_NAV_VISIBLEDISABLED   5021
#define IDI_GUIED_NAV_SCRIPTSHI         5022
#define IDI_GUIED_NAV_COLLAPSE          5023
#define IDI_GUIED_NAV_EXPAND            5024
#define IDC_GUIED_OPTIONSTAB            5200
#define IDC_GUIED_GRIDCOLOR             5201
#define IDC_GUIED_SPACINGWIDTH          5202
#define IDC_GUIED_SPACINGHEIGHT         5203
#define IDC_GUIED_GRIDVISIBLE           5204
#define IDC_GUIED_GRIDSNAP              5205
#define IDC_GUIED_WINDOWTREE            5206
#define IDC_GUIED_ITEMNAME              5207
#define IDC_GUIED_ITEMBACKGROUND        5208
#define IDC_GUIED_TYPE                  5209
#define IDC_GUIED_USEMATERIAL           5210
#define IDC_GUIED_ITEMBORDERMATERIAL    5211
#define IDC_GUIED_ITEMBACKCOLOR         5212
#define IDC_GUIED_ITEMMATCOLOR          5213
#define IDC_GUIED_ITEMFORECOLOR         5214
#define IDC_GUIED_ITEMBORDERCOLOR       5215
#define IDC_GUIED_ITEMBACKCOLORALPHA    5216
#define IDC_GUIED_ITEMTEXT              5217
#define IDC_GUIED_ITEMBORDERCOLORALPHA  5218
#define IDC_GUIED_ITEMTEXTSCALE         5219
#define IDC_GUIED_ITEMBORDERSIZE        5220
#define IDC_GUIED_ITEMMATCOLORALPHA     5221
#define IDC_GUIED_ITEMTEXTALIGNX        5222
#define IDC_GUIED_ITEMTEXTALIGNY        5223
#define IDC_GUIED_ITEMMATSCALEX         5224
#define IDC_GUIED_ITEMMATSCALEY         5225
#define IDC_GUIED_USEBACKCOLOR          5226
#define IDC_GUIED_ITEMMATCOLORSTATIC    5227
#define IDC_GUIED_ITEMKEYS              5228
#define IDC_GUIED_ADDKEY                5229
#define IDC_GUIED_EDITKEY               5230
#define IDC_GUIED_DELETEKEY             5231
#define IDC_GUIED_ITEMKEY               5232
#define IDC_GUIED_ITEMVALUE             5233
#define IDC_GUIED_ITEMVISIBLE           5234
#define IDC_GUIED_SELECTIONCOLOR        5235
#define IDC_GUIED_ALPHA                 5236
#define IDC_GUIED_ALPHASLIDER           5237
#define IDC_GUIED_SCRIPT                5238
#define IDC_GUIED_ADDVARIABLE           5239
#define IDC_GUIED_EDITVARIABLE          5240
#define IDC_GUIED_DELETEVARIABLE        5241
#define IDC_GUIED_ITEMVARIABLES         5242
#define IDC_GUIED_USETEXT               5243
#define IDC_GUIED_ITEMTEXTALIGN         5244
#define IDC_GUIED_STATIC_ALIGNMENT      5245
#define IDC_GUIED_STATIC_X              5246
#define IDC_GUIED_STATIC_Y              5247
#define IDC_GUIED_ITEMFORECOLORALPHA    5248
#define IDC_GUIED_STATIC_SCALE          5249
#define IDC_GUIED_STATIC_COLOR          5250
#define IDC_GUIED_USEBORDERCOLOR        5251
#define IDC_GUIED_STATIC_FONT           5252
#define IDC_GUIED_USEBORDERMATERIAL     5253
#define IDC_GUIED_ITEMTEXTFONT          5254
#define IDC_GUIED_STATIC_FONTSIZE       5255
#define IDC_GUIED_ITEMVARIABLEBACKGROUND 5256
#define IDC_GUIED_ITEMTEXTFONTSIZE      5257
#define IDC_GUIED_XSCALE_STATIC         5258
#define IDC_GUIED_YSCALE_STATIC         5259
#define IDC_GUIED_ITEMNOEVENTS          5260
#define IDC_GUIED_ITEMNOCLIP            5261
#define IDC_GUIED_ITEMNOCLIP2           5262
#define IDC_GUIED_ITEMNOCURSOR          5263
#define IDC_GUIED_ITEMNOTIME            5264
#define IDC_GUIED_ITEMRECTX             5265
#define IDC_GUIED_ITEMRECTW             5266
#define IDC_GUIED_IGNOREDESKTOP         5267
#define IDC_GUIED_ITEMRECTH             5268
#define IDC_GUIED_ITEMTEXTNOWRAP        5269
#define IDC_GUIED_ITEMRECTY             5270
#define IDC_GUIED_ITEMTEXTSCALE_SPIN    5273
#define IDC_GUIED_HAND                  5274
#define IDD_CONSOLE_FORM                6002
#define IDD_FIND                        6003
#define IDD_MATERIALEDIT_FORM           6004
#define IDR_ME_MAINFRAME                6005
#define IDI_MATERIALED                  6005
#define IDR_ME_MATERIALTREE_POPUP       6006
#define IDR_ME_FILETOOLBAR              6007
#define IDR_ME_STAGELIST_POPUP          6008
#define IDB_ME_TREEBITMAP               6009
#define IDI_ME_ON_ICON                  6010
#define IDI_ME_OFF_ICON                 6011
#define IDI_ME_DISABLED_ICON            6012
#define IDR_ME_EDIT_MENU                6014
#define ID_EDITMENU_INSERTFILE          6015
#define IDC_MATERIALEDITOR_EDIT_TEXT    6200
#define IDC_CONSOLE_OUTPUT              6203
#define IDC_EDIT_FINDTEXT               6204
#define IDC_CONSOLE_EDIT                6206
#define IDC_CHECK_MATCH_CASE            6207
#define IDC_CHECK_NAME_ONLY             6208
#define IDC_CHECK_MATCH_WORD            6209
#define IDC_RADIO_SEARCHFILE            6210
#define IDC_RADIO_SEARCHSCOPE           6211
#define IDC_RADIO_SEARCHALL             6212
#define IDC_MATERIAL_NAME               6213
#define IDD_DIALOG_PARTICLE_EDITOR      7000
#define IDC_BUTTON_UPDATE               7200
#define IDC_BUTTON_SAVE_PARTICLE        7201
#define IDC_COMBO_PARTICLES             7202
#define IDC_BUTTON_NEW                  7203
#define IDC_LIST_STAGES                 7204
#define IDC_BUTTON_ADDSTAGE             7205
#define IDC_BUTTON_REMOVESTAGE          7206
#define IDC_EDIT_MATERIAL               7207
#define IDC_BUTTON_BROWSEMATERIAL       7208
#define IDC_EDIT_DEPTHHACK              7209
#define IDC_CHECK_ONESHOT               7210
#define IDC_EDIT_COUNT                  7211
#define IDC_SLIDER_COUNT                7212
#define IDC_CHECK_WORLDGRAVITY          7213
#define IDC_EDIT_TIME                   7214
#define IDC_SLIDER_TIME                 7215
#define IDC_EDIT_TIMEOFFSET             7216
#define IDC_EDIT_BUNCHING               7217
#define IDC_EDIT_DEADTIME               7218
#define IDC_RADIO_RECT                  7219
#define IDC_RADIO_SPHERE                7220
#define IDC_RADIO_CYLINDER              7221
#define IDC_CHECK_ENTITYCOLOR           7224
#define IDC_EDIT_XSIZE                  7225
#define IDC_EDIT_ZSIZE                  7226
#define IDC_EDIT_YSIZE                  7227
#define IDC_EDIT_RINGOFFSET             7228
#define IDC_RADIO_CONE                  7229
#define IDC_RADIO_OUTWARD               7230
#define IDC_EDIT_DIRECTIONPARM          7231
#define IDC_RADIO_VIEW                  7232
#define IDC_RADIO_AIMED                 7233
#define IDC_RADIO_X                     7234
#define IDC_RADIO_Y                     7235
#define IDC_RADIO_Z                     7236
#define IDC_CHECK_RANDOMANGLE2          7238
#define IDC_CHECK_RANDOMDISTRIBUTION    7239
#define IDC_EDIT_CYCLES                 7240
#define IDC_EDIT_COLOR                  7241
#define IDC_BUTTON_BROWSECOLOR          7242
#define IDC_EDIT_SPEEDFROM              7243
#define IDC_EDIT_SPEEDTO                7244
#define IDC_EDIT_ROTATIONFROM           7245
#define IDC_EDIT_ROTATIONTO             7246
#define IDC_EDIT_SIZEFROM               7247
#define IDC_EDIT_SIZETO                 7248
#define IDC_EDIT_ASPECTFROM             7249
#define IDC_EDIT_ASPECTTO               7250
#define IDC_EDIT_FADECOLOR              7251
#define IDC_BUTTON_BROWSEFADECOLOR      7252
#define IDC_EDIT_FADEIN                 7253
#define IDC_EDIT_FADEOUT                7254
#define IDC_EDIT_ANIMFRAMES             7255
#define IDC_EDIT_ANIMRATE               7256
#define IDC_EDIT_GRAVITY                7257
#define IDC_EDIT_OFFSET                 7258
#define IDC_STATIC_DIRPARM              7259
#define IDC_BUTTON_HIDESTAGE            7260
#define IDC_RADIO_VIEWORIGIN            7261
#define IDC_EDIT_CUSTOMPARMS            7262
#define IDC_CHECK_EDITPARTICLEMODE      7263
#define IDC_RADIO_VIEWPROJECTILE        7264
#define IDC_EDIT_FADEFRACTION           7265
#define IDC_BUTTON_SAVE_PARTICLE_AS     7266
#define IDC_RADIO_VIEWIMPACT            7267
#define IDC_BUTTON_BROWSECOLOR_ENTITY   7268
#define IDC_BUTTON_SAVE_ONENTITY        7269
#define IDC_BUTTON_SHOWSTAGE            7270
#define IDC_RADIO_VIEWEXPLOSION         7271
#define IDC_BUTTON_SAVE_PARTICLEENTITIES 7272
#define IDC_EDIT_ORIENTATIONPARM1       7273
#define IDC_EDIT_ORIENTATIONPARM2       7274
#define IDC_SLIDER_BUNCHING             7275
#define IDC_SLIDER_SPEEDFROM            7276
#define IDC_SLIDER_SPEEDTO              7277
#define IDC_SLIDER_SIZEFROM             7278
#define IDC_SLIDER_SIZETO               7279
#define IDC_SLIDER_ROTATIONFROM         7280
#define IDC_SLIDER_ROTATIONTO           7281
#define IDC_SLIDER_ASPECTFROM           7282
#define IDC_SLIDER_ASPECTTO             7283
#define IDC_SLIDER_GRAVITY              7284
#define IDC_SLIDER_FADEIN               7285
#define IDC_SLIDER_FADEOUT              7286
#define IDC_COMBO_CUSTOMPATH            7287
#define IDC_STATIC_INFILE               7288
#define IDC_BUTTON_TESTMODEL            7289
#define IDC_BUTTON_IMPACT               7290
#define IDC_BUTTON_MUZZLE               7291
#define IDC_BUTTON_FLIGHT               7292
#define IDC_BUTTON_SELECTED             7293
#define IDC_BUTTON_DOOM                 7294
#define IDC_BUTTON_DROPEMITTER          7295
#define IDC_BUTTON1                     7296
#define IDC_BUTTON_VECTOR               7297
#define IDC_SLIDER_FADEFRACTION         7298
#define IDC_EDIT_BOUNDSEXPANSION        7299
#define IDC_STATIC_DESC                 7300
#define IDC_EDIT_INITIALANGLE           7301
#define IDC_BUTTON_XDN                  7302
#define IDC_BUTTON_XUP                  7303
#define IDC_BUTTON_YUP                  7304
#define IDC_BUTTON_YDN                  7305
#define IDC_BUTTON_ZUP                  7306
#define IDC_BUTTON_ZDN                  7307
#define IDC_BUTTON_SAVE                 8226
#define IDC_EDIT1                       8230
#define IDS_TRUE                        9000
#define IDS_FALSE                       9001
#define IDS_NOITEMSEL                   9002
#define IDS_SELFORINFO                  9003
#define ID_UNDO                         9005
#define ID_CUT                          9006
#define ID_COPY                         9007
#define ID_PASTE                        9008
#define ID_EDIT_DELETE                  9009
#define ID_EDIT_SELECTALL               9010
#define IDI_MAINFRAME_EDITOR           9013
#define IDC_SPLITTER                    9200
#define IDC_FPOINT                      9201
#define IDD_FINDTEXTURE                 10000
#define IDD_ENTITY                      10001
#define IDD_FINDBRUSH                   10003
#define IDD_ROTATE                      10004
#define IDD_SIDES                       10005
#define IDD_ABOUT                       10006
#define IDD_SURFACE                     10007
#define IDD_TEXLIST                     10012
#define IDD_DLG_PREFS                   10013
#define IDD_DLG_MAPINFO                 10014
#define IDD_DLG_ENTITYLIST              10015
#define IDD_DLG_COMMANDLIST             10018
#define IDD_DLG_INFORMATION             10019
#define IDD_DLG_GROUP                   10020
#define IDD_DLG_CAMERA                  10021
#define IDD_DLG_CAMERAEVENT             10022
#define IDD_DLG_CAMERATARGET            10023
#define IDD_DLG_WAIT                    10024
#define IDD_DIALOG_SCALE                10025
#define IDD_DIALOG_FINDREPLACE          10026
#define IDD_DIALOG_TEXTURELIST          10029
#define IDD_DIALOG_NEWPATCH             10030
#define IDD_DIALOG_TEXTURELAYOUT        10031
#define IDD_DIALOG_CAP                  10032
#define IDD_DIALOG_THICKEN              10033
#define IDD_DIALOG_PATCH                10034
#define IDD_DIALOG_LIGHT                10035
#define IDD_DIALOG_ENTITY               10036
#define IDD_DIALOG_COLORS               10037
#define IDD_DIALOG_INSPECTORS           10038
#define IDD_DIALOG_TEXTURE              10039
#define IDD_DIALOG_PREVIEW              10040
#define IDD_DIALOG_CONSOLE              10041
#define IDD_DIALOG_COMMENTS             10042
#define IDD_DIALOG_EDITVIEW             10043
#define IDD_DIALOG_EDITPREVIEW          10044
#define IDD_DIALOG_NEW_INSPECTORS       10045
#define IDD_DIALOG_NEWCURVE             10046
#define IDD_DIALOG_GETSTRING            10047
#define IDD_ENTFINDREPLACE              10048
#define IDR_ACCELERATOR1                10049
#define IDR_ACCEL_SURFACE               10050
#define IDR_MINIACCEL                   10051
#define IDR_MAINFRAME                   10052
#define IDR_RADIANTYPE                  10053
#define IDR_SHADERTYPE                  10055
#define IDR_TOOLBAR                     10058
#define IDR_MENU_DROP                   10059
#define IDR_POPUP_TEXTURE               10062
#define IDR_POPUP_SELECTION             10063
#define IDR_POPUP_VIEW                  10064
#define IDR_POPUP_GROUP                 10065
#define IDR_POPUP_SPLINE                10066
#define IDR_POPUP_MATERIAL              10067
#define IDR_POPUP_ENTITY                10068
#define IDB_IENDCAP                     10069
#define IDB_ENDCAP                      10070
#define IDB_BEVEL                       10071
#define IDB_IBEVEL                      10072
#define IDB_VIEWDEFAULT2                10076
#define IDB_VIEWDEFAULT3                10077
#define IDB_BITMAP_GROUPS               10079
#define IDB_BITMAP_MATERIAL             10080
#define IDB_BITMAP_HSB                  10081
#define IDB_BITMAP_RGB                  10082
#define IDC_VIEWDEFAULT                 10200
#define IDC_VIEWDEFAULT_Z               10201
#define IDC_SELECT                      10202
#define IDC_APPLY                       10203
#define IDC_REFRESH                     10204
#define IDC_BUTTON_RELOAD               10205
#define IDC_BUTTON_ADD                  10206
#define IDC_BUTTON_OPEN                 10207
#define IDC_APPLY2                      10208
#define IDC_APPLY_DIFFERENT             10209
#define IDC_BUTTON_PLAY                 10210
#define IDC_TESTCAMERA                  10212
#define IDC_CHECK_LIVE                  10213
#define IDC_BTN_HIDE                    10214
#define IDC_SPIN1                       10215
#define IDC_SPIN2                       10216
#define IDC_SPIN3                       10217
#define IDC_RADIO2                      10218
#define IDC_RADIO3                      10219
#define IDC_RADIO_VIEWTYPE              10220
#define IDC_RADIO_FALLOFF2              10221
#define IDC_RADIO_VIEWTYPE2             10222
#define IDC_RADIO_FALLOFF3              10223
#define IDC_RADIO_VIEWTYPE3             10224
#define IDC_LIST_ENTITIES               10225
#define IDC_RADIO_VIEWTYPE4             10226
#define IDC_EDIT_TOTALBRUSHES           10227
#define IDC_CHECK_AUTOSAVE              10229
#define IDC_CHECK_LOADLASTMAP           10230
#define IDC_LIST_ENTITY                 10231
#define IDC_EDIT_NAME                   10235
#define IDC_LIST_COMMANDS               10237
#define IDC_CHECK_LIGHTDRAW             10242
#define IDC_CHECK_SNAPT                 10243
#define IDC_EDIT_AUTOSAVE               10248
#define IDC_CHK_FLAT                    10249
#define IDC_CHECK_NEWMAPFORMAT          10250
#define IDC_BTN_ADD                     10254
#define IDC_BTN_TEXTURE                 10255
#define IDC_BTN_PREVIEW                 10256
#define IDC_BTN_ADDTARGET               10257
#define IDC_BTN_SET                     10258
#define IDC_BUTTON_MODEL                10260
#define IDC_SPIN_AUTOSAVE               10261
#define IDC_BTN_DEL                     10262
#define IDC_BUTTON_SOUND                10263
#define IDC_CHECK_SIZEPAINT             10264
#define IDC_BTN_EDIT                    10265
#define IDC_BUTTON_GUI                  10266
#define IDC_EDIT_X                      10267
#define IDC_SPIN_UNDO                   10268
#define IDC_BTN_HIDEALL                 10269
#define IDC_BUTTON_PARTICLE             10270
#define IDC_CHECK_SNAPSHOTS             10271
#define IDC_BTN_SHOWALL                 10272
#define IDC_BUTTON_SKIN                 10273
#define IDC_EDIT_FIND                   10274
#define IDC_SPIN_POINTSIZE              10275
#define IDC_BUTTON_CURVE                10276
#define IDC_EDIT_REPLACE                10277
#define IDC_EDIT_S                      10278
#define IDC_CHECK_SELECTED              10279
#define IDC_EDIT_T                      10280
#define IDC_CHECK_FORCE                 10281
#define IDC_ROTATE_BOX                  10283
#define IDC_ROTZ                        10284
#define IDC_EDIT_TOTALENTITIES          10285
#define IDC_EDIT_Y                      10286
#define IDC_EDIT_KEY                    10287
#define IDC_EDIT_INPUT                  10288
#define IDC_EDIT_PATH                   10289
#define IDC_PARTICLE_EDIT2              10290
#define IDC_ROTY                        10291
#define IDC_EDIT_NET                    10292
#define IDC_EDIT_Z                      10293
#define IDC_EDIT_COMMENTS               10294
#define IDC_E_VALUE_FIELD               10295
#define IDC_E_LIST                      10296
#define IDC_E_COMMENT                   10297
#define IDC_E_PROPS                     10298
#define IDC_E_135                       10299
#define IDC_E_180                       10300
#define IDC_E_225                       10301
#define IDC_E_270                       10302
#define IDC_E_90                        10303
#define IDC_E_45                        10304
#define IDC_E_0                         10305
#define IDC_E_315                       10306
#define IDC_E_UP                        10307
#define IDC_E_DOWN                      10308
#define IDC_E_DELPROP                   10310
#define IDC_E_STATUS                    10312
#define IDC_SHIFT_BOX                   10313
#define IDC_HSHIFT                      10314
#define IDC_VSHIFT                      10315
#define IDC_ROTATEV                     10316
#define IDC_HSTRETCH                    10317
#define IDC_SCALEV                      10318
#define IDC_EDIT_STATUSPOINTSIZE        10319
#define IDC_SCALEH                      10320
#define IDC_EDIT_ROTATION               10321
#define IDC_EDIT_UNDOLEVELS             10323
#define IDC_HSCALE                      10324
#define IDC_VSCALE                      10325
#define IDC_ROTATE                      10328
#define IDC_SLIDER_CAMSPEED             10330
#define IDC_STATIC_KEY                  10334
#define IDC_FIND_BRUSH                  10335
#define IDC_STATIC_VALUE                10337
#define IDC_E_KEY_FIELD                 10339
#define IDC_FIND_ENTITY                 10341
#define IDC_SIDES                       10343
#define IDC_COMBO_WHATGAME              10345
#define IDC_ROTX                        10346
#define IDC_BTN_COLOR                   10347
#define IDC_STATIC_COLOR                10348
#define IDC_ABOUT_GLVENDOR              10350
#define IDC_ABOUT_GLVERSION             10351
#define IDC_BTN_THECOLOR                10352
#define IDC_ABOUT_GLRENDERER            10353
#define IDC_STATIC_STUFF                10354
#define IDC_TEXTURE                     10355
#define IDC_CHECK_ALTDRAG               10356
#define IDC_SPIN_HSHIFT                 10358
#define IDC_CHECK_MOUSECHASE            10359
#define IDC_SPIN_VSHIFT                 10361
#define IDC_CHECK_FACECOLOR             10362
#define IDC_SPIN_VSCALE                 10364
#define IDC_CHECK_NOCLAMP               10365
#define IDC_SPIN_HSCALE                 10367
#define IDC_SPIN_ROTATE                 10369
#define IDC_CHECK_DLLENTITIES           10373
#define IDC_CHECK_BUGGYICD              10377
#define IDC_CHECK_HICOLOR               10382
#define IDC_CHECK_SHADERTEST            10384
#define IDC_CHECK_SHOWSHADERS           10386
#define IDC_ABOUT_GLEXTENSIONS          10387
#define IDC_LIST_TEXTURES               10388
#define IDC_COMBO_WIDTH                 10389
#define IDC_COMBO_HEIGHT                10390
#define IDC_BTN_PATCHDETAILS            10391
#define IDC_BTN_PATCHRESET              10392
#define IDC_BTN_PATCHNATURAL            10393
#define IDC_RADIO_CAP                   10394
#define IDC_BTN_PATCHFIT                10395
#define IDC_RADIO_CAP2                  10396
#define IDC_CHECK_SEAMS                 10397
#define IDC_BTN_FLIPX                   10398
#define IDC_RADIO_CAP3                  10399
#define IDC_EDIT_AMOUNT                 10400
#define IDC_BTN_FLIPY                   10401
#define IDC_RADIO_CAP4                  10402
#define IDC_BTN_ASSIGNSOUND             10403
#define IDC_BTN_AXIAL                   10404
#define IDC_BTN_ASSIGNMODEL             10405
#define IDC_BTN_FACEFIT                 10406
#define IDC_BTN_BRUSHFIT                10409
#define IDC_LIST_EVENTS                 10410
#define IDC_PARTICLE_LIST1              10412
#define IDC_LIST_VARS                   10413
#define IDC_TREE_TEXTURES               10415
#define IDC_COMBO_ROW                   10416
#define IDC_COMBO_COL                   10417
#define IDC_COMBO_TYPE                  10418
#define IDC_EDIT_WIDTH                  10419
#define IDC_EDIT_HEIGHT                 10421
#define IDC_SPIN_WIDTH                  10422
#define IDC_SPIN_HEIGHT                 10423
#define IDC_TREE_GROUP                  10425
#define IDC_CHECK_NOSTIPPLE             10426
#define IDC_TAB_MODE                    10427
#define IDC_CHECK_POINT                 10428
#define IDC_CHECK_EQUALRADIUS           10429
#define IDC_RADIO_FALLOFF               10430
#define IDC_CHECK_PROJECTED             10431
#define IDC_CHECK_EXPLICITFALLOFF       10432
#define IDC_CHECK_CENTER                10433
#define IDC_SLIDER_BRIGHTNESS           10434
#define IDC_CHECK_PARALLEL              10435
#define IDC_CHECK_SHADOWS               10436
#define IDC_CHECK_DIFFUSE               10437
#define IDC_CHECK_SPECULAR              10438
#define IDC_EDIT_RADIUSY                10439
#define IDC_EDIT_RADIUSZ                10440
#define IDC_EDIT_RADIUSX                10441
#define IDC_EDIT_TARGETX                10442
#define IDC_EDIT_TARGETY                10443
#define IDC_EDIT_TARGETZ                10444
#define IDC_EDIT_RIGHTX                 10445
#define IDC_EDIT_RIGHTY                 10446
#define IDC_EDIT_RIGHTZ                 10447
#define IDC_EDIT_UPX                    10448
#define IDC_EDIT_UPY                    10449
#define IDC_EDIT_UPZ                    10450
#define IDC_EDIT_STARTX                 10451
#define IDC_EDIT_STARTY                 10452
#define IDC_EDIT_STARTZ                 10453
#define IDC_EDIT_ENDX                   10454
#define IDC_EDIT_ENDY                   10455
#define IDC_EDIT_ENDZ                   10456
#define IDC_EDIT_CENTERX                10457
#define IDC_COMBO_TEXTURE               10458
#define IDC_EDIT_CENTERY                10459
#define IDC_EDIT_MAPS                   10460
#define IDC_EDIT_CENTERZ                10461
#define IDC_EDIT_CAM_NAME               10462
#define IDC_COMBO_SPLINES               10463
#define IDC_SCROLLBAR_SEGMENT           10464
#define IDC_EDIT_LENGTH                 10465
#define IDC_EDIT_SEGMENT                10466
#define IDC_BTN_ADDEVENT                10467
#define IDC_BTN_DELEVENT                10468
#define IDC_CHECK_TRACKCAMERA           10469
#define IDC_RADIO_EVENT                 10470
#define IDC_EDIT_TOTALSEGMENTS          10471
#define IDC_RADIO5                      10472
#define IDC_RADIO6                      10473
#define IDC_RADIO7                      10474
#define IDC_RADIO8                      10475
#define IDC_EDIT_PARAM                  10476
#define IDC_RADIO9                      10477
#define IDC_RADIO_FIXED                 10478
#define IDC_RADIO10                     10479
#define IDC_RADIO11                     10480
#define IDC_RADIO_EDITPOINTS            10481
#define IDC_RADIO12                     10482
#define IDC_RADIO_EDITPOINTS2           10483
#define IDC_BTN_DELETEPOINTS            10484
#define IDC_RADIO13                     10485
#define IDC_EDIT_TYPE                   10486
#define IDC_RADIO14                     10487
#define IDC_BTN_SELECTALL               10488
#define IDC_RADIO15                     10489
#define IDC_CHECK_SUBDIVIDE             10490
#define IDC_RADIO16                     10491
#define IDC_SLIDER_HORZ                 10492
#define IDC_SLIDER_VERT                 10493
#define IDC_EDIT_HORZ                   10494
#define IDC_EDIT_VERT                   10495
#define IDC_LOAD                        10496
#define IDC_PREVIEW                     10497
#define IDC_CHECK_HIDEROOT              10498
#define IDC_CHECK_ABSOLUTE              10499
#define IDC_LIGHTPREVIEW                10500
#define IDC_BUTTON_COLOR1               10501
#define IDC_STATIC_RGB_RECT             10502
#define IDC_STATIC_HSB_RECT             10503
#define IDC_EDIT_RED                    10504
#define IDC_SPIN_RED                    10505
#define IDC_EDIT_GREEN                  10506
#define IDC_SPIN_GREEN                  10507
#define IDC_EDIT_BLUE                   10508
#define IDC_SPIN_BLUE                   10509
#define IDC_BUTTON_COLOR2               10510
#define IDC_STATIC_NEWCOLOR             10511
#define IDC_EDIT_HUE                    10512
#define IDC_SPIN_HUE                    10513
#define IDC_ANIMATION_SLIDER            10514
#define IDC_EDIT_SAT                    10515
#define IDC_SPIN_SAT                    10516
#define IDC_BTN_APPLY                   10517
#define IDC_EDIT_VAL                    10518
#define IDC_SPIN_VAL                    10519
#define IDC_EDIT_OVERBRIGHT             10520
#define IDC_SPIN_OVERBRIGHT             10521
#define IDC_WAITSTR                     10522
#define IDC_COMBO_CLASS                 10523
#define IDC_EDIT_INFO                   10524
#define IDC_LIST_KEYVAL                 10525
#define IDC_BUTTON_BROWSE               10526
#define IDC_BUTTON_CREATE               10527
#define IDC_CUSTOM1                     10528
#define IDC_TAB_INSPECTOR               10529
#define IDC_STATIC_TITLE                10530
#define IDC_STATIC_VAL                  10531
#define IDC_TREE_MEDIA                  10532
#define IDC_EDIT_CONSOLE                10533
#define IDC_STATIC_LINE                 10535
#define IDC_BUTTON_GOTO                 10536
#define IDC_EDIT_GOTO                   10537
#define IDC_EDIT_LINE                   10538
#define IDC_ENTITY_PLAY_ANIM            10539
#define IDC_ENTITY_ANIMATIONS           10540
#define IDC_ENTITY_STOP_ANIM            10541
#define IDC_ENTITY_CURRENT_ANIM         10542
#define IDC_COMBO_CURVES                10543
#define IDC_EDIT_FIND_KEY               10544
#define IDC_EDIT_FIND_VALUE             10545
#define IDC_EDIT_REPLACE_KEY            10546
#define IDC_EDIT_REPLACE_VALUE          10547
#define IDC_KEYCOPY                     10548
#define IDC_VALUECOPY                   10549
#define IDC_CHECK_FIND_WHOLESTRINGMATCHONLY 10550
#define IDC_REPLACE                     10551
#define IDC_FIND                        10552
#define IDC_PROMPT                      10553
#define IDC_CHECK_SELECTALLMATCHING     10554
#define IDD_DIALOG_CAMERA               10555
#define IDD_DIALOG_XY                   10556
#define IDD_DIALOG_XZ                   10557
#define IDD_DIALOG_YZ                   10558
#define IDD_DIALOG_Z                    10559
#define ID_VIEW_INSPECTOR               10560
#define IDD_DIALOG_SCRIPTEDITOR         11000
#define IDR_ACCELERATOR_SCRIPTEDITOR    11001
#define IDC_SCRIPTEDITOR_EDIT_TEXT      11200
#define IDD_DIALOG_SOUND                12000
#define IDD_DIALOG_SOUNDGROUP           12001
#define IDC_EDIT_SOUND_NAME             12200
#define IDC_EDIT_VOLUME                 12201
#define IDC_EDIT_MINDIST                12202
#define IDC_EDIT_MAXDIST                12203
#define IDC_EDIT_LEADTHROUGH            12204
#define IDC_BTN_SAVEMAP                 12205
#define IDC_BTN_SAVEMAPAS               12206
#define IDC_BTN_EDIT_SOUND              12207
#define IDC_LIST_GROUPS                 12208
#define IDC_EDIT_WAIT                   12209
#define IDC_TREE_SOUNDS                 12210
#define IDC_BTN_SWITCHTOGAME            12211
#define IDC_BTN_APPLY_SOUND             12212
#define IDC_BTN_REFRESHSPEAKERS         12213
#define IDC_BTN_REFRESH                 12214
#define IDC_BTN_PLAYSOUND               12215
#define IDC_EDIT_SHADER                 12216
#define IDC_CHECK_PLAY                  12217
#define IDC_CHECK_OMNI                  12218
#define IDC_CHECKP_TRIGGERED            12219
#define IDC_CHECK_OCCLUSION             12220
#define IDC_EDIT_GROUP                  12221
#define IDC_BTN_DROP                    12222
#define IDC_BTN_GROUP                   12223
#define IDC_CHECK_PLAIN                 12224
#define IDC_BTN_REFRESHWAVE             12225
#define IDC_BTN_XDN                     12226
#define IDC_BTN_XUP                     12227
#define IDC_BTN_YUP                     12228
#define IDC_BTN_YDN                     12229
#define IDC_BTN_ZUP                     12230
#define IDC_BTN_ZDN                     12231
#define IDC_COMBO_SPEAKERS              12232
#define IDC_CHECK_GROUPONLY             12233
#define IDC_COMBO_GROUPS                12234
#define IDC_BTN_UP                      12235
#define IDC_BTN_DOWN                    12236
#define IDC_STATIC_WAVESIZE             12237
#define IDC_EDIT_RANDOM                 12238
#define IDC_BTN_TRIGGER                 12239
#define IDC_CHECK_LOOPING               12240
#define IDC_CHECK_UNCLAMPED             12241
#define IDC_EDIT_SHAKES                 12243
#define ID_DBG_FILE_MRU                 22000
#define ID_DBG_FILE_OPEN                22001
#define ID_DBG_FILE_EXIT                22003
#define ID_DBG_WINDOW_CLOSEALL          22004
#define ID_DBG_DEBUG_TOGGLEBREAKPOINT   22005
#define ID_DBG_DEBUG_RUN                22006
#define ID_DBG_DEBUG_BREAK              22007
#define ID_DBG_FILE_NEXT                22008
#define ID_DBG_DEBUG_STEPOVER           22009
#define ID_DBG_FILE_CLOSE               22010
#define ID_DBG_DEBUG_STEPINTO           22011
#define ID_DBG_DEBUG_STEPOUT            22012
#define ID_DBG_DEBUG_QUICKWATCH         22013
#define ID_DBG_DEBUG_RUNTOCURSOR        22014
#define ID_DBG_DEBUG_SHOWNEXTSTATEMENT  22015
#define ID_DBG_EDIT_COPY                22016
#define ID_DBG_EDIT_CUT                 22017
#define ID_DBG_EDIT_PASTE               22018
#define ID_DBG_EDIT_FIND                22019
#define ID_DBG_EDIT_FINDSELECTED        22020
#define ID_DBG_EDIT_FINDNEXT            22021
#define ID_DBG_EDIT_FINDPREV            22022
#define ID_DBG_EDIT_FINDSELECTEDPREV    22023
#define ID_DBG_HELP_ABOUT               22024
#define ID_DBG_SEND_COMMAND             22025
#define ID_DECLEDITOR_FIND_NEXT         23000
#define ID_DECLEDITOR_GOTOLINE          23001
#define ID_GUIED_NEW_HTMLDEF            25000
#define ID_GUIED_ITEM_NEWSLIDERDEF      25001
#define ID_GUIED_FILE_EXIT              25002
#define ID_GUIED_HELP_ABOUT             25003
#define ID_GUIED_WINDOW_CLOSEALL        25004
#define ID_GUIED_FILE_NEW               25005
#define ID_GUIED_FILE_OPEN              25006
#define ID_GUIED_FILE_CLOSE             25007
#define ID_GUIED_VIEW_ZOOMIN            25008
#define ID_GUIED_VIEW_ZOOMOUT           25009
#define ID_GUIED_FILE_SAVE              25010
#define ID_GUIED_FILE_SAVEAS            25011
#define ID_GUIED_VIEW_SHOWGRID          25012
#define ID_GUIED_VIEW_SNAPTOGRID        25013
#define ID_GUIED_VIEW_GRIDSETTINGS      25014
#define ID_GUIED_EDIT_CUT               25015
#define ID_GUIED_EDIT_COPY              25016
#define ID_GUIED_EDIT_PASTE             25017
#define ID_GUIED_VIEW_OPTIONS           25018
#define ID_GUIED_EDIT_REDO              25019
#define ID_GUIED_VIEW_HIDESELECTED      25020
#define ID_GUIED_VIEW_SHOWHIDDEN        25021
#define ID_GUIED_EDIT_UNDO              25022
#define ID_GUIED_EDIT_DELETE            25023
#define ID_GUIED_WINDOW_TILE            25024
#define ID_GUIED_WINDOW_SHOWNAVIGATOR   25025
#define ID_GUIED_FILE_MRU               25026
#define ID_GUIED_ITEM_NEWEDITDEF        25027
#define ID_GUIED_ITEM_NEWSCRIPTDEF      25028
#define ID_GUIED_ITEM_PROPERTIES        25029
#define ID_GUIED_ITEM_ARRANGEBRINGFORWARD 25030
#define ID_GUIED_ITEM_ARRANGESENDTOBACK 25031
#define ID_GUIED_ITEM_ARRANGESENDBACKWARD 25032
#define ID_GUIED_ITEM_ARRANGEBRINGTOFRONT 25033
#define ID_GUIED_ITEM_ALIGNLEFTS        25034
#define ID_GUIED_ITEM_ALIGNCENTERS      25035
#define ID_GUIED_ITEM_ALIGNRIGHTS       25036
#define ID_GUIED_ITEM_ALIGNTOPS         25037
#define ID_GUIED_ITEM_ALIGNMIDDLES      25038
#define ID_GUIED_ITEM_ALIGNBOTTOMS      25039
#define ID_GUIED_ITEM_MAKESAMESIZEWIDTH 25040
#define ID_GUIED_ITEM_MAKESAMESIZEHEIGHT 25041
#define ID_GUIED_ITEM_MAKESAMESIZEBOTH  25042
#define ID_GUIED_ITEM_SCRIPTS           25043
#define ID_GUIED_ITEM_ARRANGEMAKECHILD  25044
#define ID_GUIED_TOOLS_VIEWER           25045
#define ID_GUIED_WINDOW_CASCADE         25046
#define ID_GUIED_ITEM_NEWWINDOWDEF      25047
#define ID_GUIED_VIEW_UNHIDESELECTED    25048
#define ID_GUIED_WINDOW_SHOWTRANSFORMER 25049
#define ID_GUIED_TOOLS_RELOADMATERIALS  25050
#define ID_GUIED_ITEM_NEWHTMLDEF        25055
#define ID_GUIED_VIEW_STATUSBAR         25056
#define ID_GUIED_ITEM_NEWCHOICEDEF      25057
#define ID_GUIED_ITEM_NEWBINDDEF        25058
#define ID_GUIED_ITEM_NEWLISTDEF        25059
#define ID_GUIED_WINDOW_SHOWPROPERTIES  25060
#define ID_GUIED_ITEM_NEWRENDERDEF      25061
#define ID_GUIED_VIEWER_PAUSE           25062
#define ID_GUIED_VIEWER_PLAY            25063
#define ID_GUIED_VIEWER_START           25064
#define ID_ME_FILE_EXIT                 26000
#define ID_ME_FILE_OPEN                 26001
#define ID_ME_FILE_SAVE                 26002
#define ID_ME_FILE_NEW                  26003
#define ID_ME_FILE_SAVEAS               26004
#define ID_VIEW_INCLUDEFILENAME         26005
#define ID_PREVIEW_RELOADARBPROGRAMS    26006
#define ID_ME_PREVIEW_APPLYCHANGES      26007
#define ID_ME_PREVIEW_APPLYALL          26008
#define ID_POPUP_APPLYCHANGES           26009
#define ID_ME_FILE_SAVEMATERIAL         26010
#define ID_ME_FILE_SAVEFILE             26011
#define ID_POPUP_SAVEMATERIAL           26012
#define ID_POPUP_SAVEFILE               26013
#define ID_POPUP_SAVEALL                26014
#define ID_POPUP_APPLYFILE              26015
#define ID_POPUP_APPLYALL               26018
#define ID_POPUP_APPLYMATERIAL          26020
#define ID_ME_PREVIEW_APPLYFILE         26021
#define ID_STAGEPOPUP_ADDSTAGE          26022
#define ID_STAGEPOPUP_ADDBUMPMAP        26023
#define ID_STAGEPOPUP_ADDDIFFUSEMAP     26024
#define ID_STAGEPOPUP_ADDSPECULAR       26025
#define ID_STAGEPOPUP_DELETESTAGE       26026
#define ID_STAGEPOPUP_RENAMESTAGE       26028
#define ID_STAGEPOPUP_DELETEALLSTAGES   26029
#define ID_PREVIEW_RELOADIMAGES         26030
#define ID_POPUP_ADDMATERIAL            26031
#define ID_POPUP_DELETEMATERIAL         26032
#define ID_POPUP_RENAMEMATERIAL         26033
#define ID_POPUP_ADDFOLDER              26034
#define ID_ME_EDIT_UNDO                 26035
#define ID_ME_EDIT_REDO                 26036
#define ID_ME_EDIT_CUT                  26037
#define ID_ME_EDIT_COPY                 26039
#define ID_ME_EDIT_PASTE                26040
#define ID_ME_EDIT_DELETE               26041
#define ID_POPUP_CUT                    26042
#define ID_POPUP_COPY                   26043
#define ID_POPUP_PASTE                  26044
#define ID_STAGEPOPUP_CUT               26045
#define ID_STAGEPOPUP_COPY              26046
#define ID_STAGEPOPUP_PASTE             26047
#define ID_STAGEPOPUP_ADD               26048
#define ID_ME_EDIT_FIND                 26049
#define ID_ME_EDIT_RENAME               26050
#define ID_POPUP_RELOADFILE             26051
#define ID_FIND_NEXT                    26052
#define ID_ME_FILE_SAVE_ACEL            26060
#define ID_ME_EDIT_FIND_NEXT            26061
#define ID_TOGGLE_MISECELEANOS          29000
#define ID_DMAP                         29003
#define ID_COLOR_SUPERMAL               30000
#define ID_DROP_VIEWOPTIONS             30002
#define ID_VIEWOPTIONS_WIREFRAME        30003
#define ID_WIREFRAME_ON                 30004
#define ID_WIREFRAME_OFF                30005
#define ID_VIEWOPTIONS_FORCEVISIBILITY  30006
#define ID_FORCEVISIBILITY_ON           30007
#define ID_FORCEVISIBILITY_OFF          30008
#define ID_PATCH_NURBEDITOR             30010
#define ID_PRECISION_CURSOR_CYCLE       30011
#define ID_THEMES_MAX                   30012
#define ID_MATERIALS_GENERATEMATERIALSLIST 30013
#define ID_MATERIAL_EDIT                30014
#define ID_SELECT_ALLTARGETS            30015
#define ID_VIEW_SHOWCOMBATNODES         30016
#define ID_FILE_IMPORT                  30017
#define ID_VIEW_XY                      30018
#define ID_VIEW_SIDE                    30019
#define ID_VIEW_FRONT                   30020
#define ID_CAMERATOGGLE                 30021
#define ID_VIEW_CAMERATOGGLE            30022
#define ID_TEXTURES_POPUP               30023
#define ID_POPUP_SELECTION              30024
#define ID_VIEW_CHANGE                  30025
#define ID_VIEW_CAMERAUPDATE            30026
#define ID_VIEW_CLIPPER                 30027
#define ID_PREFS                        30028
#define ID_TOGGLE_LOCK                  30029
#define ID_EDIT_MAPINFO                 30030
#define ID_EDIT_ENTITYINFO              30031
#define ID_BRUSH_SCRIPTS                30032
#define ID_VIEW_NEXTVIEW                30033
#define ID_HELP_COMMANDLIST             30034
#define ID_SNAPTOGRID                   30036
#define ID_SPLIT_SELECTED               30037
#define ID_CLIP_SELECTED                30038
#define ID_FLIP_CLIP                    30039
#define ID_TOGGLEVIEW_YZ                30040
#define ID_TOGGLEVIEW_XZ                30041
#define ID_COLORS_GRIDTEXT              30042
#define ID_COLORS_BRUSH                 30043
#define ID_COLORS_SELECTEDBRUSH         30044
#define ID_COLORS_CLIPPER               30045
#define ID_COLORS_GRIDBLOCK             30046
#define ID_COLORS_VIEWNAME              30047
#define ID_COLOR_SETORIGINAL            30048
#define ID_COLOR_SETQER                 30049
#define ID_COLOR_SETBLACK               30050
#define ID_BYEBYE                       30051
#define ID_SELECT_SCALE                 30052
#define ID_SELECT_MOUSEROTATE           30053
#define ID_TEXTURE_REPLACESELECTED      30054
#define ID_TEXTURE_REPLACEALL           30055
#define ID_SELECT_COMPLETE_ENTITY       30056
#define ID_SCALELOCKX                   30057
#define ID_SCALELOCKY                   30058
#define ID_SCALELOCKZ                   30059
#define ID_VIEW_CUBICCLIPPING           30060
#define ID_VIEW_CUBEOUT                 30062
#define ID_VIEW_CUBEIN                  30063
#define ID_NODES_LOADNODES              30064
#define ID_NODES_SHOWNODES              30065
#define ID_NODES_SHOWLINKS              30066
#define ID_NODES_REMOVEALLNODES         30067
#define ID_NODES_COUNTNODES             30068
#define ID_NODES_GIVEMONEYTONELNO       30069
#define ID_FILE_SAVEREGION              30070
#define ID_FILE_LOADREGION              30071
#define ID_SELECTION_MOVEDOWN           30072
#define ID_SELECTION_MOVEUP             30074
#define ID_BRUSH_MAKECONE               30076
#define ID_TEXTURES_LOAD                30077
#define ID_TOGGLE_ROTATELOCK            30078
#define ID_CURVE_CYLINDER               30079
#define ID_CURVE_ENDCAP                 30080
#define ID_CURVE_BEVEL                  30081
#define ID_CURVE_SPHERE                 30082
#define ID_CURVE_HEMISPHERE             30083
#define ID_CURVE_QUARTER                30084
#define ID_CURVE_EIGHTHSPHERE           30085
#define ID_CURVE_INVERTCURVE            30086
#define ID_FILE_IMPORTMAP               30087
#define ID_FILE_EXPORTMAP               30088
#define ID_EDIT_LOADPREFAB              30089
#define ID_VIEW_SHOWCURVES              30090
#define ID_SELECTION_SELECT_NUDGELEFT   30091
#define ID_SELECTION_SELECT_NUDGERIGHT  30092
#define ID_SELECTION_SELECT_NUDGEUP     30093
#define ID_SELECTION_SELECT_NUDGEDOWN   30094
#define ID_TEXTURES_LOADLIST            30095
#define ID_DONTSELECTCURVE              30096
#define ID_CONVERTCURVES                30097
#define ID_DYNAMIC_LIGHTING             30098
#define ID_PATCH_SHOWBOUNDINGBOX        30099
#define ID_CURVE_SIMPLEPATCHMESH        30100
#define ID_PATCH_WIREFRAME              30101
#define ID_PATCH_WELD                   30102
#define ID_CURVE_PATCHTUBE              30103
#define ID_CURVE_PATCHCONE              30104
#define ID_CURVE_PATCHENDCAP            30105
#define ID_CURVE_PATCHBEVEL             30106
#define ID_CURVE_PATCHINVERTEDENDCAP    30107
#define ID_CURVE_PATCHINVERTEDBEVEL     30108
#define ID_PATCH_DRILLDOWN              30109
#define ID_CURVE_LOADPATCHFILE          30110
#define ID_CURVE_INSERTROW              30111
#define ID_CURVE_INSERTCOLUMN           30112
#define ID_CURVE_DELETEROW              30113
#define ID_CURVE_DELETECOLUMN           30114
#define ID_PATCH_INSDEL                 30115
#define ID_CURVE_INSERT_ADDCOLUMN       30116
#define ID_CURVE_INSERT_INSERTCOLUMN    30117
#define ID_CURVE_INSERT_ADDROW          30118
#define ID_CURVE_INSERT_INSERTROW       30119
#define ID_CURVE_DELETE_FIRSTCOLUMN     30120
#define ID_CURVE_DELETE_LASTCOLUMN      30121
#define ID_CURVE_DELETE_FIRSTROW        30122
#define ID_CURVE_DELETE_LASTROW         30123
#define ID_CURVE_NEGATIVE               30124
#define ID_PATCH_BEND                   30125
#define ID_CURVE_PATCHDENSETUBE         30126
#define ID_CURVE_PATCHVERYDENSETUBE     30127
#define ID_CURVE_CAP                    30128
#define ID_CURVE_CAP_INVERTEDBEVEL      30129
#define ID_CURVE_CAP_INVERTEDENDCAP     30130
#define ID_CURVE_REDISPERSE_ROWS        30131
#define ID_CURVE_REDISPERSE_COLS        30132
#define ID_PATCH_NATURALIZE             30133
#define ID_CURVE_PATCHSQUARE            30134
#define ID_BRUSH_PRIMITIVES_SPHERE      30135
#define ID_BRUSH_PRIMITIVES_TORUS       30136
#define ID_TEXTURES_TEXTUREWINDOWSCALE_200 30137
#define ID_TEXTURES_TEXTUREWINDOWSCALE_100 30138
#define ID_TEXTURES_TEXTUREWINDOWSCALE_50 30139
#define ID_TEXTURES_TEXTUREWINDOWSCALE_25 30140
#define ID_TEXTURES_TEXTUREWINDOWSCALE_10 30141
#define ID_CURVE_NEGATIVETEXTUREX       30142
#define ID_TEXTURES_FLUSH               30143
#define ID_CURVE_OVERLAY_SET            30144
#define ID_CURVE_OVERLAY_CLEAR          30145
#define ID_CURVE_NEGATIVETEXTUREY       30146
#define ID_CURVE_THICKEN                30147
#define ID_CURVE_CYCLECAP               30148
#define ID_CURVE_CYCLECAPALT            30149
#define ID_CURVE_MATRIX_TRANSPOSE       30150
#define ID_TEXTURES_RELOADSHADERS       30152
#define ID_VIEW_ENTITIESAS_BOUNDINGBOX  30153
#define ID_VIEW_ENTITIESAS_WRITEFRAME   30154
#define ID_VIEW_ENTITIESAS_SELECTEDWIREFRAME 30155
#define ID_VIEW_ENTITIESAS_SELECTEDSKINNED 30156
#define ID_VIEW_ENTITIESAS_SKINNED      30157
#define ID_VIEW_ENTITIESAS_SKINNEDANDBOXED 30158
#define ID_SHOW_ENTITIES                30159
#define ID_VIEW_ENTITIESAS_WIREFRAME    30160
#define ID_VIEW_SHOWHINT                30161
#define ID_VIEW_OPENGLLIGHTING          30162
#define ID_VIEW_SHOWCAULK               30163
#define ID_VIEW_SHOWANGLES              30164
#define ID_EDIT_SAVEPREFAB              30165
#define ID_CURVE_MOREENDCAPSBEVELS_SQUAREENDCAP 30166
#define ID_CURVE_MOREENDCAPSBEVELS_SQUAREBEVEL 30167
#define ID_CURVE_PRIMITIVES_SPHERE      30168
#define ID_VIEW_HIDESHOW_HIDESELECTED   30169
#define ID_VIEW_HIDESHOW_SHOWHIDDEN     30170
#define ID_TEXTURES_SHADERS_SHOW        30171
#define ID_SELECTION_CSGADD             30172
#define ID_VIEW_HIDESHOW_HIDENOTSELECTED 30173
#define ID_SELECTION_CSGMERGE           30174
#define ID_TEXTURES_FLUSH_UNUSED        30175
#define ID_DROP_GROUP_REMOVE            30176
#define ID_DROP_GROUP_ADDTO_WORLD       30177
#define ID_DROP_GROUP_NEWGROUP          30178
#define ID_DROP_GROUP_NAME              30179
#define ID_DROP_GROUP_ADDTO             30180
#define ID_SHOW_LIGHTVOLUMES            30181
#define ID_SHOW_LIGHTTEXTURES           30182
#define ID_SHOW_DOOM                    30183
#define ID_SPLINES_MODE                 30184
#define ID_SPLINES_LOAD                 30185
#define ID_SPLINES_SAVE                 30186
#define ID_MATERIAL_INFO                30187
#define ID_SPLINE_TEST                  30188
#define ID_POPUP_NEWCAMERA_INTERPOLATED 30189
#define ID_POPUP_NEWCAMERA_SPLINE       30190
#define ID_POPUP_NEWCAMERA_FIXED        30191
#define ID_SELECTION_MOVEONLY           30192
#define ID_SELECT_BRUSHESONLY           30193
#define ID_SELECT_BYBOUNDINGBRUSH       30194
#define ID_TEXTURES_HIDEALL             30195
#define ID_SELECTION_COMBINE            30196
#define ID_PATCH_COMBINE                30197
#define ID_VIEW_RENDERMODE              30198
#define ID_VIEW_REBUILDRENDERDATA       30199
#define ID_VIEW_REALTIMEREBUILD         30200
#define ID_VIEW_RENDERENTITYOUTLINES    30201
#define ID_VIEW_MATERIALANIMATION       30202
#define ID_DROP_NEWMODEL                30203
#define ID_SELECT_AXIALTEXTURE_BYWIDTH  30204
#define ID_SELECT_AXIALTEXTURE_BYHEIGHT 30205
#define ID_SELECT_AXIALTEXTURE_ARBITRARY 30206
#define ID_VIEW_RENDERSELECTION         30208
#define ID_VIEW_SHOW_SHOWVISPORTALS     30209
#define ID_SELECT_NOMODELS              30210
#define ID_VIEW_RENDERSOUND             30211
#define ID_SOUND_POPUP                  30212
#define ID_SOUND_SHOWSOUNDVOLUMES       30213
#define ID_SOUND_SHOWSELECTEDSOUNDVOLUMES 30214
#define ID_VIEW_SHOW_NODRAW             30215
#define ID_SELECT_MOUSESCALE            30216
#define ID_SELECTION_EXPORT_TOCM        30217
#define ID_SPLINES_EDITPOINTS           30218
#define ID_SPLINES_ADDPOINTS            30219
#define ID_SPLINES_INSERTPOINTS         30220
#define ID_SPLINES_DELETEPOINTS         30221
#define ID_FILE_EXIT                    30224
#define ID_FILE_SAVEAS                  30225
#define ID_VIEW_CENTER                  30226
#define ID_VIEW_UPFLOOR                 30227
#define ID_VIEW_DOWNFLOOR               30228
#define ID_BRUSH_FLIPX                  30229
#define ID_BRUSH_FLIPY                  30230
#define ID_BRUSH_FLIPZ                  30231
#define ID_BRUSH_ROTATEX                30232
#define ID_BRUSH_ROTATEY                30233
#define ID_BRUSH_ROTATEZ                30234
#define ID_FILE_POINTFILE               30240
#define ID_VIEW_100                     30241
#define ID_VIEW_75                      30242
#define ID_VIEW_50                      30243
#define ID_VIEW_25                      30244
#define ID_VIEW_12                      30245
#define ID_TEXTURES_SHOWALL             30246
#define ID_TEXTURES_SHOWINUSE           30247
#define ID_TEXTURES_TOGGLEVIEW          30248
#define ID_SELECTION_CREATEENTITY       30249
#define ID_SELECTION_EDITENTITY         30250
#define ID_REGION_OFF                   30252
#define ID_REGION_SETXY                 30253
#define ID_REGION_SETBRUSH              30254
#define ID_SELECTION_MAKEHOLLOW         30255
#define ID_SELECTION_SELECTPARTIALTALL  30256
#define ID_SELECTION_SELECTCOMPLETETALL 30257
#define ID_SELECTION_CSGSUBTRACT        30258
#define ID_SELECTION_SELECTTOUCHING     30259
#define ID_VIEW_NEAREST                 30260
#define ID_VIEW_NEARESTMIPMAP           30261
#define ID_VIEW_LINEAR                  30262
#define ID_VIEW_BILINEAR                30263
#define ID_VIEW_BILINEARMIPMAP          30264
#define ID_VIEW_TRILINEAR               30265
#define ID_TEXTURES_WIREFRAME           30266
#define ID_TEXTURES_FLATSHADE           30267
#define ID_VIEW_SHOWNAMES               30268
#define ID_VIEW_ZOOMIN                  30269
#define ID_VIEW_ZOOMOUT                 30270
#define ID_VIEW_SHOWCOORDINATES         30271
#define ID_VIEW_Z100                    30272
#define ID_VIEW_ZZOOMIN                 30273
#define ID_VIEW_ZZOOMOUT                30274
#define ID_SELECTION_CLONE              30275
#define ID_SELECTION_DESELECT           30276
#define ID_SELECTION_DELETE             30277
#define ID_SELECTION_DRAGVERTECIES      30278
#define ID_SELECTION_DRAGEDGES          30279
#define ID_REGION_SETTALLBRUSH          30280
#define ID_SELECTION_SELECTINSIDE       30281
#define ID_VIEW_SHOWENT                 30285
#define ID_VIEW_SHOWPATH                30286
#define ID_VIEW_SHOWLIGHTS              30287
#define ID_VIEW_SHOWCLIP                30288
#define ID_VIEW_SHOWWATER               30289
#define ID_VIEW_SHOWWORLD               30290
#define ID_MISC_TEXTUREBACKGROUN        30291
#define ID_TEXTUREBK                    30292
#define ID_COLORS_XYBK                  30293
#define ID_FILE_ABOUT                   30294
#define ID_VIEW_CONSOLE                 30295
#define ID_VIEW_ENTITY                  30296
#define ID_VIEW_TEXTURE                 30297
#define ID_COLORS_MAJOR                 30298
#define ID_COLORS_MINOR                 30299
#define ID_SELECTION_CONNECT            30300
#define ID_MISC_FINDBRUSH               30302
#define ID_MISC_NEXTLEAKSPOT            30303
#define ID_MISC_PREVIOUSLEAKSPOT        30304
#define ID_BRUSH_3SIDED                 30305
#define ID_BRUSH_4SIDED                 30306
#define ID_BRUSH_5SIDED                 30307
#define ID_BRUSH_6SIDED                 30308
#define ID_BRUSH_7SIDED                 30309
#define ID_BRUSH_8SIDED                 30310
#define ID_BRUSH_9SIDED                 30311
#define ID_SELECTION_ARBITRARYROTATION  30312
#define ID_BRUSH_ARBITRARYSIDED         30313
#define ID_SELECTION_UNGROUPENTITY      30314
#define ID_MISC_SELECTENTITYCOLOR       30315
#define ID_HELP_ABOUT                   30317
#define ID_EDIT_COPYBRUSH               30318
#define ID_EDIT_PASTEBRUSH              30319
#define ID_TEXTURES_INSPECTOR           30320
#define ID_VIEW_SHOWDETAIL              30321
#define ID_SELECTION_MAKE_DETAIL        30322
#define ID_SELECTION_MAKE_STRUCTURAL    30323
#define ID_REGION_SETSELECTION          30324
#define ID_VIEW_SHOWBLOCKS              30325
#define ID_CAMERA_UP                    30326
#define ID_CAMERA_DOWN                  30327
#define ID_CAMERA_LEFT                  30328
#define ID_CAMERA_RIGHT                 30329
#define ID_CAMERA_FORWARD               30330
#define ID_CAMERA_BACK                  30331
#define ID_CAMERA_ANGLEUP               30332
#define ID_CAMERA_ANGLEDOWN             30333
#define ID_CAMERA_STRAFELEFT            30334
#define ID_CAMERA_STRAFERIGHT           30335
#define ID_GRID_TOGGLE                  30336
#define ID_ENTITYLIST                   30337
#define ID_MAPINFO                      30338
#define ID_TOGGLECONSOLE                30339
#define ID_TOGGLECAMERA                 30340
#define ID_TOGGLEZ                      30341
#define ID_TOGGLEVIEW                   30342
#define ID_SELECTION_TEXTURE_DEC        30343
#define ID_SELECTION_TEXTURE_INC        30344
#define ID_SELECTION_TEXTURE_FIT        30345
#define ID_SELECTION_TEXTURE_ROTATECLOCK 30346
#define ID_SELECTION_TEXTURE_ROTATECOUNTER 30347
#define ID_SELECTION_TEXTURE_SCALEUP    30348
#define ID_SELECTION_TEXTURE_SCALEDOWN  30349
#define ID_SELECTION_TEXTURE_SHIFTLEFT  30350
#define ID_SELECTION_TEXTURE_SHIFTRIGHT 30351
#define ID_SELECTION_TEXTURE_SHIFTUP    30352
#define ID_SELECTION_TEXTURE_SHIFTDOWN  30353
#define ID_GRID_NEXT                    30354
#define ID_GRID_PREV                    30355
#define ID_SELECTION_TEXTURE_SCALELEFT  30356
#define ID_SELECTION_TEXTURE_SCALERIGHT 30357
#define ID_SELECTION_PRINT              30358
#define ID_SELECTION_TOGGLESIZEPAINT    30359
#define ID_PATCH_TAB                    30360
#define ID_PATCH_ENTER                  30361
#define ID_SELECT_SNAPTOGRID            30362
#define ID_PATCH_INSPECTOR              30363
#define ID_SELECT_ALL                   30364
#define ID_CURVE_FREEZE                 30365
#define ID_CURVE_UNFREEZE               30366
#define ID_CURVE_UNFREEZEALL            30367
#define ID_SELECT_RESELECT              30368
#define ID_FITBRUSH                     30369
#define ID_FITFACE                      30370
#define ID_VIEW_CROSSHAIR               30371
#define ID_SELECTION_INVERT             30372
#define ID_VIEW_GROUPS                  30373
#define ID_PROJECTED_LIGHT              30374
#define ID_SPLINES_POPUP                30375
#define ID_SELECTION_CENTER_ORIGIN      30376
#define ID_CURVE_INCREASE_VERT          30377
#define ID_CURVE_DECREASE_VERT          30378
#define ID_CURVE_INCREASE_HORZ          30379
#define ID_CURVE_DECREASE_HORZ          30380
#define ID_GRID_START                   30381
#define ID_GRID_POINT0625               30382
#define ID_GRID_POINT125                30383
#define ID_GRID_POINT25                 30384
#define ID_GRID_POINT5                  30385
#define ID_GRID_1                       30386
#define ID_GRID_2                       30387
#define ID_GRID_4                       30388
#define ID_GRID_8                       30389
#define ID_GRID_16                      30390
#define ID_GRID_32                      30391
#define ID_GRID_64                      30392
#define ID_GRID_END                     30393
#define ID_INSPECTOR_MEDIABROWSER       30394
#define ID_VIEW_GAME                    30395
#define ID_PATCH_NATURALIZEALT          30396
#define ID_VIEW_SHOWTRIGGERS            30397
#define ID_AUTOCAULK                    30398
#define ID_MISC_FINDORREPLACEENTITY     30399
#define ID_MISC_FINDNEXTENT             30401
#define ID_SELECTION_VIEW_WIREFRAMEON   30402
#define ID_SELECTION_VIEW_WIREFRAMEOFF  30403
#define ID_SELECTION_VIEW_VISIBLEON     30404
#define ID_SELECTION_VIEW_VISIBLEOFF    30405
#define ID_SCRIPTEDITOR_FIND_NEXT       31000
#define ID_SCRIPTEDITOR_GOTOLINE        31001
#define ID_ENTITY_START                 40000
#define ID_ENTITY_END                   45000
#define IDD_NEWNAME                     45000
#define IDD_RENDERBUMPFLAT              45001
#define IDD_TOOLS_OPEN                  45002
#define IDD_DIALOG_GOTOLINE             45003
#define IDB_TOOLS_OPEN                  45004
#define IDB_TOOLS_BACK                  45005
#define IDC_TOOLS_EDITNAME              45006
#define IDC_TOOLS_BACK                  45007
#define IDC_TOOLS_LOOKIN                45008
#define IDC_TOOLS_FILENAME              45009
#define IDC_TOOLS_FILELIST              45010
#define IDC_RBF_WIDTH                   45011
#define IDC_RBF_HEIGHT                  45012
#define IDC_RBF_FILENAME                45013
#define IDC_GOTOLINE_STATIC             45014
#define IDC_GOTOLINE_EDIT               45015
#define IDD_WAITDLG_PROGRESS            45016
#define IDC_ABOUT_TEXT                  45017
#define IDC_ABOUT_BITMAP                45018
#define IDC_GUIED_LOCK_ASPECT			45019
#define ID_GUIED_CHOOSE_MATERIAL		45020
#define ID_GUIED_APPLY_ITEM_PROPS		45021
#define ID_GUIED_EDIT_DUPLICATE			45022
#define ID_GUIED_WINDOW_SHOWITEMPROPERTIES		 45023
#define ID_GUIED_WINDOW_SHOWSCRIPTS		45024
#define IDC_PREVIEW_GUI					45025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        9025
#define _APS_NEXT_COMMAND_VALUE         29005
#define _APS_NEXT_CONTROL_VALUE         9214
#define _APS_NEXT_SYMED_VALUE           9005
#endif
#endif
